# --- Old pipeline config, commented out for backup ---
# trigger:
#   branches:
#     include:
#       - main
# 
# pool:
#   vmImage: 'ubuntu-latest'
# 
# variables:
#   app_location: '/'
#   api_location: 'api'
#   output_location: ''
# 
# steps:
# - task: AzureStaticWebApp@0
#   inputs:
#     app_location: $(app_location)
#     api_location: $(api_location)
#     output_location: $(output_location)
#     azure_static_web_apps_api_token: $(67a5e4545fd7d944410fe6cd0e8b03a40225a81377fec0cd73a54d431dee15fa02-5c9082a0-dfe5-430b-bf60-1b9bc125b4060002520056b0d100)
#   displayName: 'Build and deploy to Azure Static Web Apps'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    echo "Building API Functions..."
    cd api
    npm install
    npm run build
  displayName: 'Build API Functions'
  condition: succeeded()

- script: |
    echo "Verifying file structure..."
    ls -la
    echo "Checking index.html exists..."
    cat index.html | head -10
  displayName: 'Debug File Structure'

- task: AzureStaticWebApp@0
  inputs:
    app_location: "/"
    api_location: "api"
    output_location: ""
    skip_app_build: true
  env:
    azure_static_web_apps_api_token: $(67a5e4545fd7d944410fe6cd0e8b03a40225a81377fec0cd73a54d431dee15fa02-5c9082a0-dfe5-430b-bf60-1b9bc125b4060002520056b0d100)
