trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  submodules: true

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd api
    npm install
    npm run build
  displayName: 'Build API Functions'
  condition: succeeded()

- task: AzureStaticWebApp@0
  inputs:
    app_location: "/"
    api_location: "api"
    output_location: ""
  env:
    azure_static_web_apps_api_token: $(deployment_token)
